
networks:
  henriquebarbosa:
    name: henriquebarbosa

services:
  app:
    container_name: henriquebarbosa-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
    networks:
      - henriquebarbosa

  postgres:
    container_name: henriquebarbosa-db
    image: postgres:17
    restart: no
    volumes:
      - ./docker/postgres/data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - henriquebarbosa

  web:
    container_name: henriquebarbosa-web
    image: nginx:stable-alpine
    restart: no
    ports:
      - "85:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - henriquebarbosa

  # Database management with pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: henriquebarbosa-pgAdmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - henriquebarbosa

  # Database management with Adminer
  adminer:
    container_name: henriquebarbosa-adminer
    image: adminer
    restart: no
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - henriquebarbosa
